package vienan.app.journey.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import vienan.app.journey.model.CityBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table city.
*/
public class CityBeanDao extends AbstractDao<CityBean, Long> {

    public static final String TABLENAME = "city";

    /**
     * Properties of entity CityBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property City_name = new Property(1, String.class, "city_name", false, "CITY_NAME");
        public final static Property City_code = new Property(2, String.class, "city_code", false, "CITY_CODE");
        public final static Property Province_id = new Property(3, Integer.class, "province_id", false, "PROVINCE_ID");
    };


    public CityBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CityBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'city' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CITY_NAME' TEXT," + // 1: city_name
                "'CITY_CODE' TEXT," + // 2: city_code
                "'PROVINCE_ID' INTEGER);"); // 3: province_id
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_city__id ON city" +
                " (_id);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'city'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CityBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String city_name = entity.getCity_name();
        if (city_name != null) {
            stmt.bindString(2, city_name);
        }
 
        String city_code = entity.getCity_code();
        if (city_code != null) {
            stmt.bindString(3, city_code);
        }
 
        Integer province_id = entity.getProvince_id();
        if (province_id != null) {
            stmt.bindLong(4, province_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CityBean readEntity(Cursor cursor, int offset) {
        CityBean entity = new CityBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // city_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // city_code
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // province_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CityBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCity_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCity_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProvince_id(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CityBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CityBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
