package vienan.app.journey.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import vienan.app.journey.model.ProvinceBean;
import vienan.app.journey.model.CityBean;
import vienan.app.journey.model.CountyBean;

import vienan.app.journey.dao.ProvinceBeanDao;
import vienan.app.journey.dao.CityBeanDao;
import vienan.app.journey.dao.CountyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig provinceBeanDaoConfig;
    private final DaoConfig cityBeanDaoConfig;
    private final DaoConfig countyBeanDaoConfig;

    private final ProvinceBeanDao provinceBeanDao;
    private final CityBeanDao cityBeanDao;
    private final CountyBeanDao countyBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        provinceBeanDaoConfig = daoConfigMap.get(ProvinceBeanDao.class).clone();
        provinceBeanDaoConfig.initIdentityScope(type);

        cityBeanDaoConfig = daoConfigMap.get(CityBeanDao.class).clone();
        cityBeanDaoConfig.initIdentityScope(type);

        countyBeanDaoConfig = daoConfigMap.get(CountyBeanDao.class).clone();
        countyBeanDaoConfig.initIdentityScope(type);

        provinceBeanDao = new ProvinceBeanDao(provinceBeanDaoConfig, this);
        cityBeanDao = new CityBeanDao(cityBeanDaoConfig, this);
        countyBeanDao = new CountyBeanDao(countyBeanDaoConfig, this);

        registerDao(ProvinceBean.class, provinceBeanDao);
        registerDao(CityBean.class, cityBeanDao);
        registerDao(CountyBean.class, countyBeanDao);
    }
    
    public void clear() {
        provinceBeanDaoConfig.getIdentityScope().clear();
        cityBeanDaoConfig.getIdentityScope().clear();
        countyBeanDaoConfig.getIdentityScope().clear();
    }

    public ProvinceBeanDao getProvinceBeanDao() {
        return provinceBeanDao;
    }

    public CityBeanDao getCityBeanDao() {
        return cityBeanDao;
    }

    public CountyBeanDao getCountyBeanDao() {
        return countyBeanDao;
    }

}
