package vienan.app.journey.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table city.
 */
public class CityBean {

    private Long id;
    private String city_name;
    private String city_code;
    private Integer province_id;

    public CityBean() {
    }

    public CityBean(Long id) {
        this.id = id;
    }

    public CityBean(Long id, String city_name, String city_code, Integer province_id) {
        this.id = id;
        this.city_name = city_name;
        this.city_code = city_code;
        this.province_id = province_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCity_name() {
        return city_name;
    }

    public void setCity_name(String city_name) {
        this.city_name = city_name;
    }

    public String getCity_code() {
        return city_code;
    }

    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    public Integer getProvince_id() {
        return province_id;
    }

    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

}
