package vienan.app.journey.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table province.
 */
public class ProvinceBean {

    private Long id;
    private String province_name;
    private String province_code;

    public ProvinceBean() {
    }

    public ProvinceBean(Long id) {
        this.id = id;
    }

    public ProvinceBean(Long id, String province_name, String province_code) {
        this.id = id;
        this.province_name = province_name;
        this.province_code = province_code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProvince_name() {
        return province_name;
    }

    public void setProvince_name(String province_name) {
        this.province_name = province_name;
    }

    public String getProvince_code() {
        return province_code;
    }

    public void setProvince_code(String province_code) {
        this.province_code = province_code;
    }

}
